---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: need-20gib
      name: need-20gib
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: need-20gib
      template:
        metadata:
          labels:
            app: need-20gib
        spec:
          containers:
            - name: need-20gib
              image: quay.io/redhattraining/long-load:v1
              resources:
                requests:
                  memory: 20Gi
              ports:
                - containerPort: 3000
              readinessProbe:
                initialDelaySeconds: 10
                httpGet:
                  path: /health
                  port: 3000
              livenessProbe:
                initialDelaySeconds: 30
                httpGet:
                  path: /health
                  port: 3000
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: need-20gib
      name: need-20gib
    spec:
      ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
      selector:
        app: need-20gib
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: need-20gib
      name: need-20gib
    spec:
      port:
        targetPort: 3000
      to:
        kind: Service
        name: need-20gib
      tls:
        termination: edge
